// * OPERADORES ARITMETICOS

let x = 25.14

// * RESTA
let resta = 10 - 810

// * MULTIPLICACIÓN
let multiplicacion = 10 * 3

// * DIVISIÓN
let division = 100 / 2

// * SUMA
let suma = 15 + x

// * CONCATENACIÓN
let concat = "15" + x

// * MODULO
let modulo = 100 % 2

// * POTENCIA
let potencia = 10 ** 2

console.log(resta); // -> -800
console.log(multiplicacion); // -> 30 
console.log(division); // -> 50
console.log(suma); // -> 40.14
console.log(concat); // -> "1525.14"
console.log(modulo); // -> 0
console.log(potencia); // -> 100 
